### ISSUE TITLE
部門一括作成について

### ISSUE THREAD

**Issue by yoshifumiTakaesu** [moneyforward/invoice-api-doc#10]
いつもお世話になっております。
毎度、迅速なご回答に感謝致しております。

今回は2点ほど確認させてください。
1.取引先作成についてですが、現在こちらで確認した結果、作成時 = 1部門のみとなっているのですが、
取引先を作成時に、複数部門も一括で作成したいのですが、可能でしょうか？
2.もし、上記の処理ができない場合、対応の有無、又はいつ頃対応可能になるか教えていただけると助かります。

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。
以下回答させていただきます。

> 1.取引先作成についてですが、現在こちらで確認した結果、作成時 = 1部門のみとなっているのですが、
取引先を作成時に、複数部門も一括で作成したいのですが、可能でしょうか？

現在は不可能となります。

> 2.もし、上記の処理ができない場合、対応の有無、又はいつ頃対応可能になるか教えていただけると助かります。

将来的に対応する可能性はありますが、現時点では対応のスケジュールは立っておりません。
申し訳ございません。
必ずご意向にお応えできるとは限りませんが、今後ともお気づきの点、ご要望等ございましたらご連絡いただけますと幸いです。
よろしくお願いいたします。
