### ISSUE TITLE
アクセストークン発行時に未ログインだとログイン後にアプリケーションにリダイレクトされない

### ISSUE THREAD

**Issue by masatakanomoto** [moneyforward/invoice-api-doc#11]
アクセストークン発行時、クライアントをhttps://invoice.moneyforward.com/oauth/authorizeにリダイレクトさせた際にMFクラウド請求書にログインしていない状態だと
ログイン後にアプリケーション(redirect_uri)にリダイレクトされません。

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。

問題をご報告いただきありがとうございます。
修正後再度ご案内いたしますので、今しばらくお時間頂けますでしょうか。

よろしくお願いいたします。

**Comment by akira-hamada** [comment]
この度APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、APIに関する新規のお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
