### ISSUE TITLE
refresh_tokenの使用方法について

### ISSUE THREAD

**Issue by katao** [moneyforward/invoice-api-doc#12]
refresh_tokenの使用方法について
access_tokenの有効期限が切れた際にrefresh_tokenを使って、
同じaccess_tokenでもAPIを利用し続ける事が出来るようにする方法を教えて下さい。

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。
curlの場合のリフレッシュトークンの発行リクエストは下記のようになります

```
curl -X POST -d grant_type=refresh_token -d client_id=[CLIENT_ID] -d refresh_token=[REFRESH_TOKEN] https://invoice.moneyforward.com/oauth/token
```

ただしOAuth2のリフレッシュトークンは仕様上、@katao様の仰っている

> 同じaccess_tokenでもAPIを利用し続ける事が出来るようにする

ものではなく、あくまで有効期限が切れたアクセストークンを利用して新しいトークンを再度発行する手段となりますので、アクセストークン自体は新しいものとなります。ご了承ください。

**Comment by katao** [comment]
了解致しました、ありがとうございます。
