### ISSUE TITLE
タグの登録に関しまして

### ISSUE THREAD

**Issue by katao** [moneyforward/invoice-api-doc#13]
レポート(β)のタグ別レポートを使用したいのですが、
APIから請求書登録時にタグを登録することは可能でしょうか。
また、APIにてタグの一覧、任意のタグを持っている請求書の検索は可能でしょうか。
未実装であれば決まっている範囲で構いませんので実装予定を教えていただければと思います。

**Comment by syguer** [comment]
ご質問いただきありがとうございます。
タグの登録/更新及びタグを元にした検索は可能なのですが、ドキュメントのアップデートが遅れております。
完了次第再度こちらでお伝えいたしますので、恐れ入りますが今しばらくおまちくださいますようお願いたします。

**Comment by katao** [comment]
こちら簡単にでも良いので共有をしていただくとこは可能でしょうか。
また、ドキュメントの更新はいつごろになる予定でしょうか。

**Comment by syguer** [comment]
ご連絡が遅くなり申し訳ございません。ドキュメントの更新が完了いたしました

それぞれ以下のようなリクエストパラメーターになります。

*  タグの登録/更新
`tags`をキーとしてカンマ区切り文字列を値とする

*  タグの検索
検索パラメータ`q`にタグ名を入力する

この度はお待たせしてしまい申し訳ありません。
よろしくお願いします。

**Comment by katao** [comment]
お忙しい中ご対応いただきありがとうございます。
確認させていただきます。
