### ISSUE TITLE
code:500 予期しないエラーが発生しました。時間をおいて再度試してください 。になる

### ISSUE THREAD

**Issue by katao** [moneyforward/invoice-api-doc#15]
現在
`curl -i -H "Authorization: BEARER [ACCESS_TOKEN]" https://invoice.moneyforward.com/api/v1/office.json`

をコンソールから叩いた際、何度試しても
`{"code":"500","errors":[{"message":"予期しないエラーが発生しました。時間をおいて再度試してください。"}]}%`
となってしまします。他のcurlでも同様の現象が起きております。
お手数ではございますが、至急確認、対応をお願いいたします。

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。
アクセスログを調査した結果、アプリケーション側の不具合が原因でしたので先ほど修正をリリースしました。
この度はご迷惑をおかけいたしました。申し訳ございません。

引き続きMFクラウド請求書をよろしくお願いいたします。

**Comment by katao** [comment]
ご返信ありがとうございます。
上記のcurlは通ったのですが、下記のcurlは未だにレスポンスが帰ってきません。
同じ不具合なのでしょうか、ご確認いただいてもよろしいでしょうか。
なお、こちらはコンソールからではなくphpから実行を行なっております。

`
$url = "https://invoice.moneyforward.com/api/v1/partners.json?page=1&per_page=100";
				$type = "GET";
				$time_out = 120;
                $ch = curl_init();
                // 保存するファイル
                $fp = fopen('./curl.log', 'a');
                // 詳細な情報を出力する
                curl_setopt($ch, CURLOPT_VERBOSE, true);
                // STDERR の代わりにエラーを出力するファイルポインタ
                curl_setopt($ch, CURLOPT_STDERR, $fp);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER,TRUE);
                curl_setopt($ch, CURLOPT_ENCODING, 'UTF-8');
                curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
                curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $time_out);
                curl_setopt($ch, CURLOPT_TIMEOUT, $time_out);
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $type);
				curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                  Content-Type: application/json',
                  "Authorization: BEARER [ACCESS_TOKEN]"
                ));
				
				$response = curl_exec($ch);
                $result = json_decode($response, true);
                fclose($fp);
                curl_close($ch);
`

**Comment by syguer** [comment]
上記リクエストをコマンドラインから下記のcurlで実行してもエラーになるかご確認いただけますでしょうか

```
curl -i -H "Authorization: BEARER [ACCESS_TOKEN]" https://invoice.moneyforward.com/api/v1/partners.json?page=1&per_page=100
```

**Comment by katao** [comment]
下記のようなリターンが返ってきて失敗いたします。
[1] 8555
zsh: no matches found: https://invoice.moneyforward.com/api/v1/partners.json?page=1                                                                           
[1]  + exit 1     curl -i -H  https://invoice.moneyforward.com/api/v1/partners.json?page=1

**Comment by katao** [comment]
`curl -i -H "Authorization: BEARER [ACCESS_TOKEN]" "https://invoice.moneyforward.com/api/v1/partners.json?page=1&per_page=100"`
こちらであれば正しく動作します。

**Comment by syguer** [comment]
ありがとうございます。
シェル上では実行可能ということでAPI側の問題ではないようでしたので、改めてスクリプトを確認させていただきました。
`CURLOPT_HTTPHEADER`の指定の引数でクオートが足りていないように見えましたので、下記のように修正したところ、動作の確認が取れましたのでご参考まで

```
<?php
$url = "https://invoice.moneyforward.com/api/v1/partners.json?page=1&per_page=100";
$type = "GET";
$time_out = 120;
$ch = curl_init();
// 保存するファイル
$fp = fopen('./curl.log', 'a');
// 詳細な情報を出力する
curl_setopt($ch, CURLOPT_VERBOSE, true);
// STDERR の代わりにエラーを出力するファイルポインタ
curl_setopt($ch, CURLOPT_STDERR, $fp);
curl_setopt($ch, CURLOPT_RETURNTRANSFER,TRUE);
curl_setopt($ch, CURLOPT_ENCODING, 'UTF-8');
// curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json')); <- この行は後半で指定しているので不要と思われます
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $time_out);
curl_setopt($ch, CURLOPT_TIMEOUT, $time_out);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $type);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
 'Content-Type: application/json', //この行のクオートが不足？
  'Authorization: BEARER [ACCESS_TOKEN]'
));

$response = curl_exec($ch);
$result = json_decode($response, true);
echo curl_getinfo($ch, CURLINFO_HTTP_CODE);
print_r($result);
fclose($fp);
curl_close($ch);
?>

**Comment by katao** [comment]
ご連絡ありがとうございます、
こちら、上記転載時にクオートが抜けてしまったようです、通常はクオートが入った状態で実行を行なっております。失礼いたしました。
現在もphpから実行を行なうと
ERR_EMPTY_RESPONSE
となってしまう現象が引き続き置いています。
curl.logにも何も入らず、api側のlogなどにそれらしいlogなどないでしょうか。

**Comment by syguer** [comment]
ご確認ありがとうございます。
弊社側のログでは正常なレスポンス(コード200)を返却しておりましたが、データ量が多いためレスポンスを返すのに1000ms弱かかっているようです。
サーバー側では特に制限はかけておりませんので、恐らくどこかのネットワークで問題が起きているのではないかと思います。（どこかの経路でtimeout時間が短く設定されている等）
ネットワーク経路のタイムアウト値をご確認いただくか、データ取得件数(per_page)を調整していただきますようお願いいたします。

**Comment by katao** [comment]
お世話になっております。
こちら確認を行ったのですが、
データ取得件数(per_page)を調整しても取得することはできませんでした。
確認なのですが、ここ1ヶ月以内にHeartbreed脆弱性対応を行ってはいないでしょうか。
現在弊社はさくらサーバーのVPSを使用しているのですが、そこデフォルトで入っているlibcurlが古く、
cUrlのバージョンがMFクラウド様にてHeartbreed脆弱性対応後のOpenSSLに対応していない状態になってしまったのではないかと考えています。

**Comment by katao** [comment]
こちらサーバー側のlibcurlを最新に変更しましたところ正常に動作することを確認できました。
ありがとうございました。

**Comment by syguer** [comment]
ご連絡が遅れてしまい申し訳ございません。
解決したとのことで何よりでございます。
引き続きよろしくお願いいたします。
