### ISSUE TITLE
見積系API

### ISSUE THREAD

**Issue by azcomedia** [moneyforward/invoice-api-doc#18]
見積系APIを追加する予定はあるでしょうか？
見積系APIで見積を作成し請求書への変換オペレーションもAPIでコントロールしたいのですが。。

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。
見積書APIについては現在実装が検討されております。
具体的なリリース時期はまだ決まっておりませんが、今夏中にはリリースされるものと思われます。
現在の検討内容ではリリース時には請求書への変換もサポートされる想定です。
大変恐れ入りますが今しばらくお待ちいただければと思います。

引き続きよろしくお願いいたします。

**Comment by fum1h1ro** [comment]
こちら既に実装されているのでしょうか。
また、納品書へアクセスするAPIの実装予定はありますか？

**Comment by akira-hamada** [comment]
@fum1h1ro

お問い合わせ頂きありがとうございます。

見積書や納品書などの請求書以外のAPIについては、引き続き実装を検討しているという状況です。
具体的なリリース時期などのスケジュールについてはお答えできませんが、今しばらくお待ちいただければと思います。また、リリース次第READMEにも反映させる予定です。

ご要望をお送り頂きありがとうございます。
引き続きよろしくお願いいたします。

**Comment by fum1h1ro** [comment]
@akira-hamada こちらの状況は進展ありますでしょうか

**Comment by akira-hamada** [comment]
@fum1h1ro お問い合わせ頂きありがとうございます。

お待たせして申し訳ございません。
見積書APIについては、開発予定を考慮の上で前向きに検討を進めております。
リリース予定をお答えできず申し訳ございませんが、今しばらくお待ち頂ければと思います。

お問い合わせ頂きありがとうございます。引き続きよろしくお願い致します。

**Comment by akira-hamada** [comment]
@shinshinshin 従来の請求書APIとバージョンは違いますが、ご利用頂けます。

従来の請求書の各APIとレスポンス構造が大きく異なるため、見積書APIは最初の公開となりますがバージョンを変えてv2としております。

**Comment by sora2019sora** [comment]
見積書APIは v2は、スマレジと連携可能でしょうか？可能であれば、連携の手順を教えてください。

**Comment by akira-hamada** [comment]
> 見積書APIは v2は、スマレジと連携可能でしょうか？可能であれば、連携の手順を教えてください。

@sora2019sora スマレジとマネーフォーワードクラウド請求書との公式な連携はサポートしておりませんので、お手数をお掛け致しますがご自身でスマレジAPI等の仕様やドキュメントをご確認の上で、弊社APIとの連携処理を実装して頂くことになります。

ご期待に沿えず申し訳ございませんが、引き続きよろしくお願い致します。

**Comment by akira-hamada** [comment]
この度APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、APIに関する新規のお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
