### ISSUE TITLE
レスポンス500サーバーエラー

### ISSUE THREAD

**Issue by accg** [moneyforward/invoice-api-doc#2]
取引先の作成を試したところ、取引先作成はできるもののレスポンス500が返ってきました。
何か推測できる要因があれば教えてください。

**Comment by syguer** [comment]
不具合をご報告いただきましてありがとうございます。

リクエストヘッダのAccept:がtext/html等になっているかもしれません。
`Accept: application/json`にして再度お試し頂けますでしょうか。

API側でも、上記が原因の場合はより詳細なエラーを返すよう修正を入れる予定です。

**Comment by accg** [comment]
ありがとうございます。
解決いたしました。
