### ISSUE TITLE
取引先登録時の都道府県について

### ISSUE THREAD

**Issue by CmHndWng** [moneyforward/invoice-api-doc#21]
APIにて取引先を登録する際に、都道府県に""、住所1に「中央区日本橋・・・」などを入れると、不正な都道府県であるとのエラーとなりました。都道府県に固定値で東京都を入れるとOKなのですが、もしかして都道府県は必須でしょうか？

**Comment by syguer** [comment]
@CmHndWng 
MFクラウド請求書APIをご利用いただきありがとうございます。
ご連絡が遅くなり申し訳ございません。
都道府県に空文字を入れてしまうと不正とみなされてしまうため、パラメーターに含めないか、nullを入れて再度お試しいただけますでしょうか。

**Comment by CmHndWng** [comment]
ご回答ありがとうございます。試してみます。

**Comment by akira-hamada** [comment]
この度APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、APIに関する新規のお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
