### ISSUE TITLE
複数の請求書に表示する敬称について

### ISSUE THREAD

**Issue by CmHndWng** [moneyforward/invoice-api-doc#22]
APIにて1つの取引先(partner)に複数の部門(department)を登録し、各部門ごとに請求書を登録した場合、2枚目以降の請求書に敬称が表示されないようです。ご確認をお願いできるでしょうか？

**Comment by syguer** [comment]
@CmHndWng MFクラウド請求書APIをご利用いただきありがとうございます。
ご連絡が遅くなり申し訳ありません。
当方にて再現テストを行いましたが、再現することができませんでした。
departmentの親となるpartnerにリクエストを送り（`GET https://invoice.moneyforward.com/api/v1/partners/:partner_id`）、レスポンスの`name_suffix`に値が入っているかをご確認いただけますでしょうか。

よろしくお願いいたします。

**Comment by akira-hamada** [comment]
この度APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、APIに関する新規のお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
