### ISSUE TITLE
請求書作成APIについて

### ISSUE THREAD

**Issue by imifu** [moneyforward/invoice-api-doc#24]

**Comment by Merrick-Zhang** [comment]
１．初回目一般的のAccessトークンを利用してユーザー情報などを取得できますが、
2回目からデータを取得できません。
２．RefreshedAPIトークンを利用すると、Accessトークンを取得でき、上記の問題を解決できますが、ただ毎回Accessトークンが変わるので、Accessトークンを保存するなどことが可能ですか？
何かアドバイスを頂けたら助かります。

**Comment by akira-hamada** [comment]
@Merrick-Zhang 返信が遅れ大変申し訳ございません。accessトークンには30日の期限がありますので、期限切れの際にはおっしゃられるようにリフレッシュトークンを利用してaccessトークンの再取得を行って頂きますようお願い致します。よってリフレッシュトークンを保存して頂く事でアクセストークンの期限切れに対応出来ると思われます。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、APIに関する新規のお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂ますようお願い致します。
