### ISSUE TITLE
APIからの請求書テンプレートの利用

### ISSUE THREAD

**Issue by seimiyajun** [moneyforward/invoice-api-doc#25]
現在MFクラウド請求書の利用を検討しております。

APIから繰越欄付き請求書テンプレートを利用したく考えておりますが可能でしょうか？
1テンプレートのみ使用のためWebページでテンプレートのデフォルトを繰越欄付きテンプレートに指定する、など事前に対応すれば良いということであれば非常にありがたく助かります。
（普通に考えれば無いような気はしていますが念のため教えていただきたく）

**Comment by syguer** [comment]
@seimiyajun 
MFクラウド請求書APIをご検討いただきありがとうございます。

> 1テンプレートのみ使用のためWebページでテンプレートのデフォルトを繰越欄付きテンプレートに指定する、など事前に対応すれば良いということであれば非常にありがたく助かります。

はい。ご認識頂いている通り、事前にweb上の「帳票設定」画面にて指定したテンプレートが自動で使用される仕様となっております。
しかし、現在のAPIでは繰越額をAPIで指定することが不可能な他、自動計算するロジックが適用されないものとなっております。
こちらの対応時期は現在未定のステータスとなっております。申し訳ございません。

引き続きMFクラウド請求書をよろしくお願いいたします。

**Comment by seimiyajun** [comment]
@syguer 承知しました。
ありがとうございます。

>しかし、現在のAPIでは繰越額をAPIで指定することが不可能な他、自動計算するロジックが適用されないものとなっております。

事前にCSVインポートは試していたので、今回いただいた回答含めて、CSVのインポートをAPIとして公開したもの（むしろAPIはCSVインポートのラッパー）だとなんとなく理解しました。

おそらくMFクラウド請求書を使うことになると思います。
その際にまた質問させていただくことがありましたらよろしくお願い致します。
