### ISSUE TITLE
請求書作成APIによる事業所の選択

### ISSUE THREAD

**Issue by seimiyajun** [moneyforward/invoice-api-doc#27]
印影などを複数事業所で使い分ける運用を考えております。
請求書作成APIで事業所を選択(指定)する方法はありますでしょうか。

**Comment by syguer** [comment]
@seimiyajun さま
MFクラウド請求書APIをご利用いただきありがとうございます。
申し訳ございません。現在APIで事業所を選択する機能はございません。
access_tokenはユーザー単位（1ログインメールアドレス単位）で発行致しておりますので、各事業所にそれぞれAPI用ユーザーをお作りいただき、複数のアクセストークンをアプリケーション側で使い分けていただくのが、現状の代替手段となります。

追加でご不明点がございましたら、お気軽にご相談ください。
引き続きよろしくお願いいたします。

**Comment by seimiyajun** [comment]
回答ありがとうございます。

>現在APIで事業所を選択する機能はございません。
>各事業所にそれぞれAPI用ユーザーをお作りいただき、複数のアクセストークンをアプリケーション側で使い分けていただく
承知しました。

念のため確認させてください。
1つの事業所のみにアクセスできるユーザーを事業所の数の分だけ用意しそのユーザーでそれぞれaccess_tokenを発行する、ということでよろしいしょうか？

**Comment by syguer** [comment]
> 念のため確認させてください。
> 1つの事業所のみにアクセスできるユーザーを事業所の数の分だけ用意しそのユーザーでそれぞれaccess_tokenを発行する、ということでよろしいしょうか？

はい。ご認識の通りとなります

**Comment by seimiyajun** [comment]
承知しました。

ありがとうございます。

**Comment by buroku** [comment]
『ユーザーを事業所の数の分だけ用意』というのは、メンバーの追加・管理　メニューからメンバー追加でよろしいのでしょうか。例えば２つの事業所を請求書APIで別々に使い分けするには、この追加したメンバーをそれぞれの別々の事業所だけにアクセスできるように設定すればよろしいのでしょうか。

**Comment by akira-hamada** [comment]
> 例えば２つの事業所を請求書APIで別々に使い分けするには、この追加したメンバーをそれぞれの別々の事業所だけにアクセスできるように設定すればよろしいのでしょうか。

@buroku 2つの事業所をAPI上でも別々に扱う場合には、2つのそれぞれの事業所(例: 事業所aとb)に対して、それぞれ別のユーザを追加して頂くような状態になります。あるいは追加せずとも事業所作成時に紐付いている最初のユーザでも問題ございません。

そのそれぞれのユーザでアクセストークンを発行して頂くようなフローになります。

**Comment by buroku** [comment]
教えていただいた通りに、新規で別のアカウントc（メールアドレス）をMFクラウド請求書で作って、元の複数事業者（a, b）が登録されているアカウントで、事業者（a）に成った後メンバーの追加・管理で、cを紐付けました。アカウントc上でAPIアプリを設定することで、APIから事業者（a）で請求書を出力できました。ただアカウントc上で、必ず事業者（a）に成っておかないとダメのようです。アカウントc（API用ユーザー）でログインしたままだと、APIから請求書を出力すると事業所cで出力されてしまいます。（ブラウザを開いているとか関係なく最後に選択した事業所になっているように思います）
このような仕様と理解して間違いないでしょうか。なにか確実に選択できればいいのですが。。 @akira-hamada
