### ISSUE TITLE
API経由による請求書作成数の制限について

### ISSUE THREAD

**Issue by HisashiImahayashi** [moneyforward/invoice-api-doc#28]
API経由による請求書作成数の制限について質問があります。
「MFクラウド請求書APIドキュメント」を拝見しますと、下記の様に記載がございます。
↓
Basicプラン以下のプランをご利用の場合、月のAPI経由での請求書作成数を100件までとさせていただきます。

この作成数の制限はアプリケーションに対してのものなのでしょうか？
それとも、アプリケーションを利用するユーザーに対してのものなのでしょうか？

例えば前者の場合、(アプリケーションのOwnerアカウントがBasicプランならば、)アプリケーションがAPI経由で作成できる請求書はユーザー数に関わらず必ず100件までとなります。
しかし後者の場合、Basicプランの2人のユーザーがそのアプリケーションを利用すると、
各ユーザーは各々100件ずつ請求書を作成できるので、アプリケーションがAPI経由で作成できる請求書は200件までとなるかと存じます。

どうぞ、ご回答のほどよろしくお願いいたします。

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。
ご説明の中の後者の、
> アプリケーションを利用するユーザーに対して

の制限が仕様となります。
ご認識の通り、現在の仕様では

> Basicプランの2人のユーザーがそのアプリケーションを利用すると、
> 各ユーザーは各々100件ずつ請求書を作成できるので、アプリケーションがAPI経由で作成できる請求書は200件> までとなるかと存じます。

このようなことも可能となります。

**Comment by HisashiImahayashi** [comment]
@syguer さま

承知いたしました。
ご回答ありがとうございます！
