### ISSUE TITLE
Windows環境からだと500エラーになる

### ISSUE THREAD

**Issue by seimiyajun** [moneyforward/invoice-api-doc#29]
同じプログラムを用いて、データを投げているのですがWindows環境のみエラーになります。
500エラーを返している理由をお教えいただけますでしょうか。

■投げたデータ
{"billing":{"department_id":"YlrN638x2nyau_9beFoqWw","title":"2017年1月5日締めご請求","billing_number":"0018787201701","note":"お支払方法：普通振込            \n ","billing_date":"2017/01/05","due_date":"","tags":"請求方法未登録","items":[]}}

■レスポンス
{"code":"500","errors":[{"message":"予期しないエラーが発生しました。時間をおいて再度試してください。"}]}

※ここに記載した請求データ自体はitemsが空のため、総額が0円になるデータということは理解しています。

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。
文字コードはUTF-8をご利用でしょうか？
SHIFT-JISをご利用の場合は、お手数ですがUTF-8で再度お試しいただけますでしょうか？

**Comment by seimiyajun** [comment]
素早い返答ありがとうございます。
UTF-8で送信しているつもりなのですが、エラーが解消されません。

こちらが送信している（貴社サーバが受信している）パラメータを貴社にてご確認いただくことはできませんでしょうか。

**Comment by syguer** [comment]
@seimiyajun 
ありがとうございます。
頂いた情報を元に検証いたしましたところ、"note"に入力されている改行コードが問題となる場合があるようです。
恐れ入りますが、Windows環境でご利用されているクライアントでは\nを文字列としてではなく改行コードとして認識してリクエストされていないか、ご確認いただくことは可能でしょうか。

**Comment by seimiyajun** [comment]
@syguer 
ありがとうございます。
改行については確認してみます。

しかし情報の後出しになり恐縮ですが、取引先の登録（改行を含まないデータ）でも同様のエラー(500)が返ってきております。
（以下のデータにつきましては顧客データが含まれるため、一部文字列を変更しております。）

■投げたデータ
{"partner":{"name":"株式会社xxxx","name_suffix":"御中","departments":[{"id":"ftE0bE8er1eQDzYuJAL-2w","zip":"xxx-xxxx","tel":"","prefecture":"佐賀県","address1":"xxxxxx１１番１１号","address2":"","person_name":"","email":"","cc_emails":""}]}}

■レスポンス
{"code":"500","errors":[{"message":"予期しないエラーが発生しました。時間をおいて再度試してください。"}]}

**Comment by syguer** [comment]
調査をしたところ、取引先については、UTF-8として読み込めない旨のエラーが発生していることを観測しました。
取引先名に機種依存文字が仕様されておりませんでしょうか（数字を◯で囲った字は旧字体など）
切り分けのため、別な取引先でも同じ症状が起きるかどうかご確認いただけますでしょうか？

また、取引先の登録におきましては、`partner: { }` の括りの中に全てのパラメーターを入れるのが正しいリスエストとなりまして、 `departments` は無視されます。
詳しくは[ドキュメント](https://github.com/moneyforward/invoice-api-doc/#取引先の作成)をご参照ください。
よろしくお願いいたします。

**Comment by seimiyajun** [comment]
ご確認が遅くなり申し訳ありません。

突き詰めて確認したところ、当初のご指摘の通りSHIFT-JISで送信しており（変換しているつもりだったが変換できていなかった）、それに起因するエラーでした。
非常に素早い回答で助かりました。

**Comment by syguer** [comment]
承知しました。
また何かあればお気軽にご連絡を頂ければと思います。
引き続きよろしくお願いいたします。
