### ISSUE TITLE
見積書・注文書に関するAPI

### ISSUE THREAD

**Issue by ikneg** [moneyforward/invoice-api-doc#3]
サポートに問合せたところ下記のような返信を頂きましたので
こちらで質問させて下さい。
"MFクラウド請求書のAPIについて、詳細な仕組みのご質問につきましては
Githubのissuesから、ご質問を頂けますと幸いです。”

1. 見積書・注文書に関してはAPIのマニュアルには記載が
ありませんでした。API経由でこれらを操作することは
貴社サービスでは不可能ですか？
  
2. フリーフォーマットのPDF等をAPI経由でアップロードし
郵送する請求書に同梱する事は今後可能対応する予定はありますか？

**Comment by syguer** [comment]
ご質問いただきありがとうございます。

> 見積書・注文書に関してはAPIのマニュアルには記載が
> ありませんでした。API経由でこれらを操作することは
> 貴社サービスでは不可能ですか？

見積書及び見積書の発注書変換機能につきましては現時点ではAPIを提供しておりません。
具体的な日程については未定とさせていただいておりますが、他の既存機能に比べますと比較的早く提供を開始できる予定ですので、アップデートをお待ち頂ければと思います。

> フリーフォーマットのPDF等をAPI経由でアップロードし
> 郵送する請求書に同梱する事は今後可能対応する予定はありますか？

対応の予定はありますが、こちらについても具体的な日程については未定となります。
申し訳ございません。

**Comment by ikneg** [comment]
承知しました。
ご回答有り難うございました。
