### ISSUE TITLE
請求書の作成APIで売上総額、消費税額を指定できないでしょうか

### ISSUE THREAD

**Issue by seimiyajun** [moneyforward/invoice-api-doc#30]
CSVでは小計(subtotal)、消費税(excise_price)、合計金額(total_price)の指定ができますが、
APIでこれらを指定して請求書登録できないでしょうか？

消費税の計算や端数の丸めが一律ではなく取引先ごとに異なるため、またその計算結果は社内システムが保持しているため、APIで請求書登録する際にこれらを指定できると非常に助かります。

**Comment by syguer** [comment]
ご要望ありがとうございます。
開発要望の一つとして開発チームで検討させていただきます。
今後ともよろしくお願いいたします。

**Comment by akira-hamada** [comment]
この度APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、APIに関する新規のお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
