### ISSUE TITLE
請求書の取引先の名前の変更方法について

### ISSUE THREAD

**Issue by h-kobayashi-sw** [moneyforward/invoice-api-doc#31]
請求書を作成後に更新APIで取引先名を変更することは可能でしょうか？

取引先マスタを変更後に再度請求書を更新しても変更されません。
新規登録時後に当時の情報からは変更しない仕様なのでしょうか？

よろしくお願いいたします。

**Comment by syguer** [comment]
@h-kobayashi-sw 
MFクラウド請求書APIをご利用いただきありがとうございます。
ご認識の通り、現在は取引先名は変更できない仕様となっております。
この仕様は今後変更となる可能性がありますが、時期未定となります。申し訳ございません。

引き続きよろしくお願いいたします。

**Comment by h-kobayashi-sw** [comment]
ありがとうございます。

取引先名のみとして質問させていただきましたが、取引先マスタから取得するデータ全てが同様ということでしょうか？

**Comment by syguer** [comment]
@h-kobayashi-sw さま
この度一部仕様変更を行い、取引先の情報を更新後、作成した請求書に同じ"department_id"が渡された場合は最新の情報に更新するように致しましたのでご連絡いたします。
また、ご質問事項の回答が遅れ、申し訳ありません。

> 取引先名のみとして質問させていただきましたが、取引先マスタから取得するデータ全てが同様ということでしょうか？

いただいたご質問に関してはご認識の通りとなります。
引き続きよろしくお願いいたします。

**Comment by h-kobayashi-sw** [comment]
ありがとうございます。
助かります。

**Comment by akira-hamada** [comment]
この度APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、APIに関する新規のお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
