### ISSUE TITLE
領収書の作成について

### ISSUE THREAD

**Issue by takemen** [moneyforward/invoice-api-doc#32]
領収書を作成するAPIをご用意いただけないでしょうか？
作成を作ると編集や削除も用意しないといけないと思うので大変かと思います。
請求書から「領収書に変換する」機能のAPIだけでも結構です
ご検討いただきたく、宜しくお願い致します。

**Comment by akira-hamada** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。

作成を含めた領収書APIについては現在実装が検討されております。
具体的なリリース時期などのスケジュールについてはお答えできませんが、
今しばらくお待ちいただければと思います。

ご要望をお送り頂きありがとうございます。
引き続きよろしくお願いいたします。

**Comment by buroku** [comment]
領収書を作成するAPIを希望しております。よろしくお願いします。

**Comment by akira-hamada** [comment]
本件について返信が遅れ大変申し訳ございません。また、領収書作成APIについて改めてご要望頂き誠にありがとうございます。

領収書作成APIについては引き続き検討中という状態ですので、大変申し訳ございませんが、今しばらくお待ち下さい。

また勝手ながら、この度APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
