### ISSUE TITLE
請求書登録時に品目コードを利用した登録について

### ISSUE THREAD

**Issue by h-kobayashi-sw** [moneyforward/invoice-api-doc#34]
https://github.com/moneyforward/invoice-api-doc#リクエスト例-11

こちらを参考に品目コードを入力した品目登録を行おうとしましたが、データが登録されません。

名前や数量を登録する場合は成功しますので、リクエストの構造が間違っていることはないと考えております。

APIを実際に送信し動作を確認しておりますが、仕様として想定している挙動について確認させてください。

- 品目コードによる登録は現時点で可能でしょうか？
- 品目コードを入力してかつ名前も合わせて送信した場合の挙動はどうなりますか？
  - コードから取得したデータに対して名前などが送信された場合は上書きとなる等
- 存在しない品目コードを送信した場合はどういう挙動になりますか？

お手数おかけしますがご確認のほどよろしくお願いいたします。

**Comment by mf-invoice-ah** [comment]
@h-kobayashi-sw 
MFクラウド請求書APIをご利用いただきありがとうございます。
また、ご返信が遅くなり大変申し訳ございません。

> 品目コードによる登録は現時点で可能でしょうか？

請求書作成時に、品目コードのみでの品目の指定は可能です。
下記のように品目(items)の値として `code`に品目コードをご指定下さい。

```bash
curl -i -H "Authorization: BEARER [YOUR_API_TOKEN]" -H "Content-Type: application/json" \
-d '
{
  "billing" : {
    "department_id" : "SOME_EXISTING_DEPARTMENT_ID",
    "items" : [
      { "code" : "THIS_IS_ITEM_CODE" }
    ]
  }
} ' \
-X POST https://invoice.moneyforward.com/api/v1/billings
```

> 品目コードを入力してかつ名前も合わせて送信した場合の挙動はどうなりますか？
> コードから取得したデータに対して名前などが送信された場合は上書きとなる等

品目APIで作成された既存の品目の品目コードを使って請求書を作成した場合は、その品目の品目名などが使われます。請求書作成APIリクエスト時に、請求書に紐づく品目の"name"で別の名前を設定してもその名前は反映されません。

> 存在しない品目コードを送信した場合はどういう挙動になりますか？

存在しない(品目一覧APIで取得できる品目の品目コードではない)品目コードを用いて請求書作成APIをリクエストした場合でも、
請求書自体は作成され、作成された請求書に存在していなかった品目コードを持った品目が紐付きますが、そこで作られた品目は品目一覧APIや品目取得APIでは取得できません。(品目一覧には登録されていません)

以上ご確認下さい。よろしくお願い致します。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
