### ISSUE TITLE
販売管理台帳のAPI

### ISSUE THREAD

**Issue by hajime9652** [moneyforward/invoice-api-doc#35]
販売管理台帳のレコードの作成・更新APIが欲しいです。

**Comment by mf-invoice-ah** [comment]
@hajime9652 
ご返信が遅れ大変申し訳ございません。

販売管理台帳のAPIに関してましては、他APIも含め実装を検討しているという状況です。
具体的なリリース時期などのスケジュールはお答えできませんが、今しばらくお待ちいただければと思います。

ご要望をお寄せ頂き誠にありがとうございます。
引き続きよろしくお願いいたします。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
