### ISSUE TITLE
請求書に表示される住所について

### ISSUE THREAD

**Issue by HM31** [moneyforward/invoice-api-doc#37]
請求書の左上に表示される住所は、取引先として登録した「都道府県＋住所1」になるようです。
取引先の作成APIを使って都道府県を未設定にて登録し、住所1に「神奈川県〜」と設定すると、都道府県の値が「東京都」と設定されてしまうため、出来上がる請求書の住所が「東京都神奈川県〜」なってしまいます。
回避する手段はないでしょうか？

**Comment by mf-invoice-ah** [comment]
@HM31 
MFクラウド請求書APIをご利用いただきありがとうございます。
また、ご返信が遅くなり大変申し訳ございません。

弊社サポートにもお問い合わせ頂き、既に把握頂いているかもしれませんが、
ご認識頂いております通り、現状では都道府県の値は必須となり未設定の場合は自動的に値として「東京都」が入力される仕様となっております。

この仕様は今後変更となる可能性がありますが、具体的なリリース時期等についてはお答え致しかねます。申し訳ございませんが、引き続きよろしくお願いいたします。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
