### ISSUE TITLE
ローカルでの開発

### ISSUE THREAD

**Issue by bibunn** [moneyforward/invoice-api-doc#38]
ローカルでの開発を検討しています。
Redirect URIを設定せず、APIを使用する方法はありますか？
正直使いづらいです。

**Comment by mf-invoice-ah** [comment]
@bibunn 
MFクラウド請求書APIをご利用いただきありがとうございます。
また、ご返信が遅くなり大変申し訳ございません。

現状の仕様としまして、お手数をお掛けしますがRedirect URIの設定は必須となります。
申し訳ございません。引き続きよろしくお願いいたします。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
