### ISSUE TITLE
アプリケーションの登録でエラーメッセージ

### ISSUE THREAD

**Issue by nbeppu** [moneyforward/invoice-api-doc#4]
「アプリケーションの登録」の際に、すべての必須項目を入力しても
「エラー内容を修正してください」
とのメッセージが表示され、アプリケーションの登録が行えません。

想定される原因はどんなものがありますでしょうか。

> 名前: test
>  Redirect URI: http://localhost/ (あるいは実在するURL、空欄）
>  Scopes: write

**Comment by syguer** [comment]
お問い合わせ頂きありがとうございます。
Redirect URIはhttpsのみ許可となっておりますので、httpsのURIで再度お試しいただけますでしょうか。
情報が不足しておりまして申し訳ございません。
よろしくお願いいたします。

**Comment by nbeppu** [comment]
解決しました。ありがとうございます。
