### ISSUE TITLE
取引先マスタのIDが変わることがある？

### ISSUE THREAD

**Issue by pandeiro245** [moneyforward/invoice-api-doc#41]
MF請求書APIを使って各取引先マスタのIDを別サーバに保存していたのですが以前、3月に取得したものが無効化され、6月現在違うIDになっているようです。

2018年3月15日：Wn-CImCvw9tP3DYt9svpMw
2018年6月20日現在：fViZsoWiJnaguKf1hy7wvw

下記にはアクセスできない
https://invoice.moneyforward.com/partners/Wn-CImCvw9tP3DYt9svpMw

下記にはアクセスできる
https://invoice.moneyforward.com/partners/fViZsoWiJnaguKf1hy7wvw 

こちら、同じ顧客マスタでもIDが変更になる条件が何かあるのでしょうか？

**Comment by mf-invoice-ah** [comment]
@pandeiro245
MFクラウド請求書APIをご利用頂きありがとうございます。

基本的に作られたデータのIDが変わる事はない仕様ですが、ご投稿頂いた情報のみですと発生している事象や原因の特定が出来かねますので、お手数お掛けしますが改めてMFクラウド請求書のカスタマサポートを通じてお問い合わせ頂けますでしょうか？

これ以上の詳しい原因究明には、お作り頂いたアプリケーションに紐づくMFクラウド請求書の事業所やユーザ情報など、お客様のデータに関する情報をお聞きする可能性がありますので、オープンなGitHub上よりもカスタマサポートを通じてのやり取りが適切かと思われます。

改めてのお問い合わせの際には `該当のOAuthアプリケーションのClient ID`もお知らせ下さい。
Client IDの確認手順は下記になります。

1. Oauthアプリケーションを作ったユーザーでMFクラウド請求書に[ログインフォームからログイン](https://invoice.moneyforward.com/user/sign_in)
1. [Oauthアプリケーション一覧](https://invoice.moneyforward.com/oauth/applications)を表示
1. 一覧中の該当のアプリケーション名をクリック
1. 表示される `Client ID`をお伝え下さい

カスタマサポートへはMFC請求書にログインしている状態で、[サポートページ](https://invoice.moneyforward.com/supports)最下部の問い合わせフォームからメール等でお問い合わせ下さい。

お手数お掛けして大変申し訳ございませんがよろしくお願い致します。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
