### ISSUE TITLE
アクセストークンの再発行コマンドでエラー

### ISSUE THREAD

**Issue by takahashi-rsvlnk** [moneyforward/invoice-api-doc#43]
MFクラウド請求書API スタートアップガイドに記載されている、アクセストークンの再発行コマンド
$ curl -d client_id=[CLIENT_ID] -d redirect_uri=[REDIRECT_URL] -d grant_type=refresh_token -d refresh_token=[REFRESH_TOKEN] -X POST https://invoice.moneyforward.com/oauth/token
を実行したところ、
以下のようなエラーが返ってきました。
{"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}
お手数ですが、ご確認いただけますでしょうか？

**Comment by ryoff** [comment]
ご指摘ありがとうございます。
確認しましたところ、スタートアップガイドに誤記がございまして、現在正しい記載へと変更させていただきました。

`-d redirect_uri=[REDIRECT_URL]` の箇所を `-d client_secret=[CLIENT_SECRET]` に変更いただき、再度お試しいただけますでしょうか。

**Comment by takahashi-rsvlnk** [comment]
実行できました。ありがとうございました。
