### ISSUE TITLE
取引先の条件取得、及び一括削除について

### ISSUE THREAD

**Issue by yoshifumiTakaesu** [moneyforward/invoice-api-doc#5]
取引先APIについて、2点確認させてください。

1.取引先のAPIですが、条件取得（=あいまい検索）をリクエストURIで指定できますでしょうか？  
>例).
> GET /api/v1/partners?code=****
> GET /api/v1/partners?name=****   

2.削除のリクエスト方式として、取引先IDを指定する仕様になっているので、
一度取引先を取得し、IDを指定しながらDELETE メソッドで削除する方法をとらせていたただいてますが、
全ての取引先を削除するリクエスト方式があればご教授お願いいたします。

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用いただきありがとうございます。

> 1.取引先のAPIですが、条件取得（=あいまい検索）をリクエストURIで指定できますでしょうか？

2015年11月現在は取引先の検索はサポートしておりません。対応をお待ち下さい。

> 2.削除のリクエスト方式として、取引先IDを指定する仕様になっているので、
> 一度取引先を取得し、IDを指定しながらDELETE メソッドで削除する方法をとらせていたただいてますが、
> 全ての取引先を削除するリクエスト方式があればご教授お願いいたします。

全ての取引先を1リクエストで削除するリクエスト方式はご用意がありません。恐れ入りますがクライアント側で実装いただく形になります。
一括削除につきましては今後実装を検討させていただきます。

よろしくお願いします。

**Comment by yoshifumiTakaesu** [comment]
迅速なご対応ありがとうございます。
一括系APIの実装を心よりお待ちしております。
