### ISSUE TITLE
データ更新の通知API

### ISSUE THREAD

**Issue by shinshinshin** [moneyforward/invoice-api-doc#50]
何らかのデータ変更をした場合にそれを通知するAPIはないのでしょうか？
MFクラウド請求書上で変更をした場合、他システムと自動的にデータの同期を図るには、他システム側から数分おきにデータが変更されていないかをチェックするようなことが必要なのでしょうか？

**Comment by akira-hamada** [comment]
@shinshinshin 申し訳ございませんが、MFクラウド請求書でのデータ変更を外部に通知するようなAPIは現在公開しておりません。

ご指摘のように、外部から明確なトリガーなしにMFクラウド請求書のデータと同期して頂くには、現状は定期的に参照APIを通じてチェックするようポーリングして頂く必要があります。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
