### ISSUE TITLE
C#からのAPI呼び出しについて

### ISSUE THREAD

**Issue by tatsunaka** [moneyforward/invoice-api-doc#53]
お世話になります。
C#からAPIを呼び出す必要がありますが、アクセストークンの渡し方、引数の渡し方が良くわかりません。
HttpWebRequest を使用するのではと当たりは付けていますが、サンプルソースがあると大変助かります。
基本的なことで申し訳ないですが、よろしくお願いいたします。

**Comment by akira-hamada** [comment]
https://github.com/moneyforward/invoice-api-doc/issues/54 でも別件ご質問頂き、そちらをcloseしましたので本issueも一旦closeさせて頂きます。また何かあれば再openして頂ければと思います。
