### ISSUE TITLE
エラーメッセージ　(406)受容不可　について

### ISSUE THREAD

**Issue by tatsunaka** [moneyforward/invoice-api-doc#54]
お世話になります。
現在動作テストを行っていまして、手始めに得意先登録を行っています。
APIをコールしますと、(406)受容不可　というエラーが返ってきます。
ただし、得意先自体は作成できている状態です。
これは何が考えられるでしょうか？
お手数ですが、よろしくお願いいたします。

**Comment by tatsunaka** [comment]
お世話になっております。

ヘッダーですが、
{Content-Type: application/json
Authorization: BEARER bfdde5e42f6a385fb8b2d30a87ce169cefb30e72a532f3374a654d33d104d3f1
Host: invoice.moneyforward.com

}

このようになっております。
先ほど17:33頃にリトライしました。
結果は同じで、(406)が返っています。
取引先は作成できています。

よろしくお願いいたします。

************************************************
   株式会社ウェルテック
       中尾　達也
    〒869-1108
   熊本県菊池郡菊陽町光の森4-16-10
　　TEL 096-233-1060
　　FAX 020-4665-4760(D-FAX) 096-233-1060
　　携帯 090-4518-1165 (IP)050-3778-6977
　　t.nakao@welltech.biz <mailto:t.nakao@welltech.biz>
************************************************

**Comment by akira-hamada** [comment]
@tatsunaka エラーの詳細をお教え頂きありがとうございます。
ご返信頂いたコメントにAPIのアクセストークンとメール署名による個人情報が記載されておりましたので、こちらの判断ですぐに削除させて頂きました。ご了承下さい。

コメント頂いた内容は弊社で記録しておりますので、内容を基に調査致します。また何か分かりましたら本issue上で連絡させて頂きます。

**Comment by tatsunaka** [comment]
お世話になります。
未だにエラー原因が特定できず困っております。
アドバイスいただけると助かります。
C# のコードになります。


            HttpWebRequest req = (HttpWebRequest)WebRequest.Create("https://invoice.moneyforward.com/api/v2/partners");

            req.Method = "POST";
            req.ContentType = "application/json";
            req.Headers.Add("Authorization: BEARER " + access_token);

            using (var streamWriter = new StreamWriter(req.GetRequestStream()))
            {
                string jsonPayload = new JavaScriptSerializer().Serialize(new
                {
                    name = "サンプル取引先",
                    name_kana = "aaaaa",
                    zip = "8691108"
                });
                streamWriter.Write(jsonPayload);
            }
            ViewBag.ErrMsg = "";
            HttpWebResponse res;
            try
            {
                res = (HttpWebResponse)req.GetResponse();    //<<ここでエラー発生 (406)受容不可
                RequestResult result;
                using (res)
                {
                    using (var resStream = res.GetResponseStream())
                    {
                    }
                }

            }
            catch(Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;
            }

**Comment by akira-hamada** [comment]
@tatsunaka ご連絡が遅れ申し訳ございません。問題の切り分けを詳しく行いために以下の2点をご確認頂けますでしょうか？お手数お掛け致しますが、よろしくお願い致します。

1. API リクエストURLの `v2`の部分を `v1`に変更してリクエストをお試し頂く
2. コードと同内容のリクエストをcurlでお試し頂く

**Comment by tatsunaka** [comment]
@akira-hamada ご連絡ありがとうございました。
1.変化ありません。なお、本日のテストでは、V1,V2とも得意先は作成されませんでした。
2.curlでのリクエストは、サポートページにあります内容と同じになるかと思いますが、正常動作を確認しております。
よろしくお願いいたします。

**Comment by akira-hamada** [comment]
@tatsunaka 早急にご対応頂きありがとうございます。
16:25および16:28頃にリクエスト頂けましたでしょうか？こちらリクエスト内容を確認しましたところ、どちらも `/api/v1/partners` へのリクエストであったんですが、2回ともHTMLとしてリクエストされておりました。

コードを拝見すると `Content-Type `ヘッダーに `application/json`を指定されていそうなんですが、実際のリクエストヘッダーの内容をそちらでご確認頂くことは可能でしょうか？

**Comment by akira-hamada** [comment]
@tatsunaka `Content-Type`として `application/json`を指定して頂く事で、こちらのサービス側でもリクエスト内容がJSONとして解釈されます。しかし、現状そうはならず、HTMLとしてリクエストが解釈されている可能性がございます。

ちなみに、ステータスコード以外のレスポンス内容(レスポンスボディなど)を可能であれば教えて頂けますでしょうか？

**Comment by akira-hamada** [comment]
@tatsunaka ご確認頂きありがとうございます。先ほど18:20 ~ 18:30のリクエストを確認いたしましたが、やはりリクエストがHTML扱いになっているため(`ContentType`の指定が効いていなさそう？)に、406エラーを返しております。

curlなどでのリクエストは正常に処理されていることから、こちらのシステム側としては今すぐにご提案できる解決案は申し訳ございませんが、すぐには出せない可能性がございます。

**Comment by tatsunaka** [comment]
お世話になります。
となりますと、具体的にどうすればよいのか、代替案をご教授頂けますと幸いです。今回C#からの接続です。マイナーすぎる言語でも無いかと思いますので、よろしくお願い申し上げます。

**Comment by akira-hamada** [comment]
@tatsunaka お待たせして申し訳ございません。

C#における[HttpWebRequestのAcceptプロパティのデフォルト値がnull](https://docs.microsoft.com/ja-jp/dotnet/api/system.net.httpwebrequest.accept?view=netframework-4.7.2#%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3%E5%80%A4)である事が406エラーの原因のようです。APIとしては `Accept`ヘッダーに `application/json`という指定を要求しているため、その指定がnull(未指定)の場合に406エラーが発生します。curlでは `Accept`ヘッダーのデフォルト値が `*/*`であるため、明示なしでも406エラーが発生しないという挙動の違いがありました。

よって4, 5行目辺りに`req.Accept = "application/json";`という指定をして頂ければエラー無くAPIリクエストできると思われますので、お試し下さい。よろしくお願い致します。

**Comment by akira-hamada** [comment]
> @akira-hamada お世話になっております。ご教授いただいた点でエラーを解消することができました。本当にありがとうございました。なお、以下のような記述になっております。

エラー解消できたとの事でご報告頂きありがとうございます。では本issueはcloseさせて頂きます。
