### ISSUE TITLE
請求書と見積書のAPI経由でのEメール送信

### ISSUE THREAD

**Issue by buroku** [moneyforward/invoice-api-doc#59]
API経由で郵送はできますがメール送信のAPIはできますか。もし出来ない場合はリリースされる予定はございますか。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
