### ISSUE TITLE
請求書作成APIに関しまして

### ISSUE THREAD

**Issue by katao** [moneyforward/invoice-api-doc#6]
請求書の作成APIを使用し、以下の用にリクエストを出したのですが、
レスポンス自体は正しく帰ってきたものの、出来上がった請求書には品目が空状態でした。
それを踏まえまして何点か質問をさせていただければと思います。

1.請求書の作成APIを使用する際は使用する品目を予め登録しておかなければならないのでしょうか。
もしそうなら同時に登録されるか、仕様書にその旨の記載をお願いしたいです。
2.MFクラウド請求書APIドキュメント(https://github.com/moneyforward/invoice-api-doc)の
作成APIのリクエスト例に品目を2つ以上指定したリクエスト例を掲載していただきたいです。(できれば、他のAPIもより実際的な例が良いかと思います。)
3.もし、請求書の作成APIを使用する際は使用する品目を予め登録しておかなければならない場合、
「品目コード」のみの指定で十分かと思うのですが、品目の名前などを指定しないといけない理由は何でしょうか。
4.こちらのAPIは契約プランに左右されることなく使用可能なのでしょうか。

お手数ではございますが、ご回答よろしくお願い致します。

curl -i -H "Authorization: BEARER [ACCESS_TOKEN]" -H "Content-Type: application/json" -d '{ "billing" : { "department_id" : "XXXXX","title": "サービス利用料","payment_condition":"◯◯銀行　XX支店 口座種別：普通口座 口座番号：0000000 口座名義：サンプル（カ","note":"恐れ入りますが、振込手数料はお客様負担でお願いいたします。","billing_date":"2015-11-27","due_date":"2015-11-27","sales_date":"2015-11-27","document_name":"請求書" }, "items":[{ "name":"AAA施作(9月)", "code":"8", "quantity":"1", "unit_price":"200000", "unit":"式" },{ "name":"BBB施工(11月)", "code":"6", "quantity":"1", "unit_price":"150000", "unit":"式" }] }' -X POST https://invoice.moneyforward.com/api/v1/billings

**Comment by syguer** [comment]
MFクラウド請求書APIをご利用頂きましてありがとうございます。
以下ご回答させていただきます。

> 1.請求書の作成APIを使用する際は使用する品目を予め登録しておかなければならないのでしょうか。
もしそうなら同時に登録されるか、仕様書にその旨の記載をお願いしたいです。

品目については予め登録する必要はありません。

> 2.MFクラウド請求書APIドキュメント(https://github.com/moneyforward/invoice-api-doc)の
作成APIのリクエスト例に品目を2つ以上指定したリクエスト例を掲載していただきたいです。(できれば、他のAPIもより実際的な例が良いかと思います。)

ご要望ありがとうございます。次回ドキュメントアップデート時に反映させていただきます。

> 3.もし、請求書の作成APIを使用する際は使用する品目を予め登録しておかなければならない場合、
「品目コード」のみの指定で十分かと思うのですが、品目の名前などを指定しないといけない理由は何でしょうか。

請求書作成APIでは品目の名前を指定する必要はありません。また上記1に対するご回答でも記載させていただきましたが、予め登録する必要もありません。
その上での補足になりますが、事前に登録している品目を使用したい場合は、品目コードのみを入力すればその他の情報を補完されるのですが、ドキュメントへの記載ができておりませんでした。
こちらについては次回ドキュメントアップデート時に反映させていただきます。

> 4.こちらのAPIは契約プランに左右されることなく使用可能なのでしょうか。

APIの使用自体はどのプランでも可能です。
その上での制限については[こちら](https://invoice.moneyforward.com/blog/api-startup-guide)のドキュメントに記載させていただいておりましたが、次回ドキュメントアップデート時にgithubのページにも反映させていただきます。


また、リクエストを拝見致しましたが、リクエストのJSONでは品目が請求書の外に出てしまっているため、品目がない状態で作成されているものと思います。

フォーマット済みリクエストJSON
```json
"billing" : { 
  "department_id" : "XXXXX",
  "title": "サービス利用料",
  "payment_condition":"◯◯銀行　XX支店 口座種別：普通口座 口座番号：0000000 口座名義：サンプル（カ",
  "note":"恐れ入りますが、振込手数料はお客様負担でお願いいたします。",
  "billing_date":"2015-11-27",
  "due_date":"2015-11-27",
  "sales_date":"2015-11-27",
  "document_name":"請求書"
}, #<= ここでbillingが閉まっている
"items":[
  {
    "name":"AAA施作(9月)",
    "code":"8",
    "quantity":"1",
    "unit_price":"200000",
    "unit":"式"
  },
  {
    "name":"BBB施工(11月)",
    "code":"6",
    "quantity":"1",
    "unit_price":"150000",
    "unit":"式"
  }
]
```

正しいリクエストは下記の形になると思われますので、こちらで再度お試し頂けますでしょうか
```json
"billing" : { 
  "department_id" : "XXXXX",
  "title": "サービス利用料",
  "payment_condition":"◯◯銀行　XX支店 口座種別：普通口座 口座番号：0000000 口座名義：サンプル（カ",
  "note":"恐れ入りますが、振込手数料はお客様負担でお願いいたします。",
  "billing_date":"2015-11-27",
  "due_date":"2015-11-27",
  "sales_date":"2015-11-27",
  "document_name":"請求書",
  "items":[
    {
      "name":"AAA施作(9月)",
      "code":"8",
      "quantity":"1",
      "unit_price":"200000",
      "unit":"式"
    },
    {
      "name":"BBB施工(11月)",
      "code":"6",
      "quantity":"1",
      "unit_price":"150000",
      "unit":"式"
    }
  ]
}
```

引き続きよろしくお願いします。

**Comment by katao** [comment]
迅速なご対応ありがとうございます。
ご回答頂きました点すべて確認させていただきました、ありがとうございます。
また、補足ではありますが、下記もご確認いただければと思います。
よろしくお願い致します。

取引先の作成APIの「都道府県(partner[prefecture])」が必須と記載があるが、バリデーションがかかっていない。
→リクエスト例にも「都道府県(partner[prefecture])」がない。

**Comment by katao** [comment]
連投で申し訳ございません、以下のソースで、
{"code":"400","errors":[{"message":"必要なパラメーターが存在しない、もしくは空です。"}]}
になるのですが、どこが原因がアドバイスをいただければと思います。
よろしくお願い致します。
```
$ch = curl_init();
curl_setopt($ch, CURLOPT_POST, 1);
$json = json_encode(
	array(
		"partner" => array(
			"name" => "test",
			"prefecture" => "東京都"
		)
	));
curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
	'Content-Type: application/json',
	'Authorization: BEARER [ACCESS_TOKEN]'
));
curl_setopt($ch, CURLOPT_URL, 'https://invoice.moneyforward.com/api/v1/billings');

curl_exec($ch);
curl_close($ch);
```

**Comment by syguer** [comment]
ご連絡が遅くなり申し訳ございません。

> 取引先の作成APIの「都道府県(partner[prefecture])」が必須と記載があるが、バリデーションがかかっていない。
> →リクエスト例にも「都道府県(partner[prefecture])」がない。

こちら、記載内容の整合性が取れておりませんでしたので修正致します。ご指摘ありがとうございます。
