### ISSUE TITLE
PHPから取引先の更新

### ISSUE THREAD

**Issue by binbin4649** [moneyforward/invoice-api-doc#60]
phpからcurlを用いて利用を検討しています。
トークンの更新、取引先の登録はできたのですが、取引先の更新をすると404が帰って来てしまいます。
下記にcurlのログを付けました。なにか分かりませんでしょうか？
よろしくおねがいします。

ちなみに、
[https://github.com/moneyforward/invoice-api-doc/blob/master/partners/update.md](https://github.com/moneyforward/invoice-api-doc/blob/master/partners/update.md)
こちらの、
> PATCH /api/v2/partners/:id

このidは、departments_idのことですよね？

curl log
1つ目二つ目は、トークンを更新したログ。
3つ目が更新のリクエストで、4つ目が404のレスポンスです。

* About to connect() to invoice.moneyforward.com port 443 (#7)
*   Trying 150.95.164.96...
* Connected to invoice.moneyforward.com (150.95.164.96) port 443 (#7)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=invoice.moneyforward.com,OU=Production,O="Money Forward, Inc.",L=MINATO-KU,ST=TOKYO,C=JP,serialNumber=0000-00-000000,incorporationCountry=JP,businessCategory=Private Organization
* 	start date:  8月 24 00:00:00 2018 GMT
* 	expire date: 10月 27 12:00:00 2019 GMT
* 	common name: invoice.moneyforward.com
* 	issuer: CN=GeoTrust TLS RSA CA G1,OU=www.digicert.com,O=DigiCert Inc,C=US
> POST /oauth/token HTTP/1.1
Host: invoice.moneyforward.com
Accept: */*
Content-Length: 257
Content-Type: application/x-www-form-urlencoded

* upload completely sent off: 257 out of 257 bytes
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Cache-control: no-cache="set-cookie"
< Content-Type: application/json; charset=utf-8
< Date: Fri, 08 Feb 2019 03:54:11 GMT
< ETag: W/"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
< Pragma: no-cache
< Set-Cookie: AWSELB=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;PATH=/;MAX-AGE=10800
< Status: 200 OK
< X-Request-Id: xxxxxxxx-xxxxxxx-xxxxxxx-xxxxxxxxxxxxxxxx
< X-Runtime: 0.025094
< Content-Length: 249
< Connection: keep-alive
< Server: Scutum
< 
* Connection #7 to host invoice.moneyforward.com left intact
* About to connect() to invoice.moneyforward.com port 443 (#8)
*   Trying 150.95.164.96...
* Connected to invoice.moneyforward.com (150.95.164.96) port 443 (#8)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=invoice.moneyforward.com,OU=Production,O="Money Forward, Inc.",L=MINATO-KU,ST=TOKYO,C=JP,serialNumber=0000-00-000000,incorporationCountry=JP,businessCategory=Private Organization
* 	start date:  8月 24 00:00:00 2018 GMT
* 	expire date: 10月 27 12:00:00 2019 GMT
* 	common name: invoice.moneyforward.com
* 	issuer: CN=GeoTrust TLS RSA CA G1,OU=www.digicert.com,O=DigiCert Inc,C=US
> POST /api/v2/partners/departments_id HTTP/1.1
Host: invoice.moneyforward.com
Accept: */*
Authorization: BEARER [ACCESS_TOKEN]
Content-Type: application/json
Content-Length: 400

* upload completely sent off: 400 out of 400 bytes
< HTTP/1.1 404 Not Found
< Cache-control: no-cache="set-cookie"
< Content-Type: text/html; charset=UTF-8
< Date: Fri, 08 Feb 2019 03:54:12 GMT
< Set-Cookie: AWSELB=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;PATH=/;MAX-AGE=10800
< Status: 404 Not Found
< Vary: Accept-Encoding
< X-Request-Id: xxxxxxxx-xxxxxxx-xxxxxxx-xxxxxxxxxxxxxxxx
< X-Runtime: 0.051464
< Content-Length: 1017
< Connection: keep-alive
< Server: Scutum
< 
* Connection #8 to host invoice.moneyforward.com left intact

**Comment by akira-hamada** [comment]
@binbin4649 
APIをご利用頂きありがとうございます。
404の原因として可能性が高いものとして、PATCH対象のIDの指定が違う事が考えられます。

> ちなみに、
> https://github.com/moneyforward/invoice-api-doc/blob/master/partners/update.md
> こちらの、
> > PATCH /api/v2/partners/:id

> このidは、departments_idのことですよね？

ご確認頂いております `/api/v2/partners/:id` のidの部分はdepartments_idではなくpartner自身のIDとなります。具体的には、取引先作成時にAPIから返却された `id`属性の値あるいは、[取引先一覧API (/api/v2/partners)](https://github.com/moneyforward/invoice-api-doc/blob/master/partners/index.md)で取得できる[各取引先の `id`属性](https://github.com/moneyforward/invoice-api-doc/blob/master/partners/responses/partners.json#L4)です。(下記jsonの4行目)

https://github.com/moneyforward/invoice-api-doc/blob/master/partners/responses/partners.json#L4

以上、ご確認の上でまた不明点がございましたらお問い合わせください。よろしくお願い致します。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関する追加のお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂きますようお願い致します。
