### ISSUE TITLE
クロスドメイン制約について

### ISSUE THREAD

**Issue by Yanchi4425** [moneyforward/invoice-api-doc#61]
kintoneをカスタマイズして、kintoneに保存されたデータ元にAjaxで本APIを叩いて請求書を作成したいと考えていますが、クロスドメイン制約により、そのままでは使用できません。

Ajaxでは本APIは利用できないのでしょうか？

そのような有償プラグインはあるようですが、違うやり方で通信しているのでしょうか？

**Comment by akira-hamada** [comment]
> Ajaxでは本APIは利用できないのでしょうか？
> そのような有償プラグインはあるようですが、違うやり方で通信しているのでしょうか？

@Yanchi4425 申し訳ございませんが当APIでは、ご指摘のようにクロスドメイン制約によってAjaxでのアクセスは想定しておりません。よって、仰られるような他プラグインに関してもAjax以外の方法でリクエストしていると思われます。

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関するお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂ますよう

**Comment by akira-hamada** [comment]
APIに関するお問い合わせフローの変更をさせて頂きますので、本issueに関するお問い合わせ及び、新規のAPIに関するお問い合わせは invoice.feedback@moneyforward.com 宛にメール頂ますようお願い致します。
