### ISSUE TITLE
請求書のPDFダウンロードリンクの取得

### ISSUE THREAD

**Issue by sngazm** [moneyforward/invoice-api-doc#62]
管理上の都合から、MFクラウドの請求書のメール送信機能ではなく、
別のCRMシステムからPDFダウンロードページのリンクを送信しようと考えています。
請求書の「メール送信」を押した時に本文中に表示されるPDFダウンロードリンクをAPIから取得したいのですが、こちらは可能でしょうか？
もし未実装であれば、今後実装の予定はありますでしょうか？
![スクリーンショット 2019-04-10 17 17 59](https://user-images.githubusercontent.com/4480229/55863328-4963db80-5bb5-11e9-97d9-03b0aa849e80.png)

**Comment by akira-hamada** [comment]
@sngazm マネーフォワード クラウド請求書APIをご利用頂きありがとうございます。

> 請求書の「メール送信」を押した時に本文中に表示されるPDFダウンロードリンクをAPIから取得したいのですが、こちらは可能でしょうか？

申し訳ございませんが、PDFダウンロードURLは現状でのAPI公開は行っておりません。

また、直近でのリリースは予定しておりませんがご要望として承りまして検討させていただきます。 ご期待に添えず申し訳ございませんが、よろしくお願い致します。

**Comment by sngazm** [comment]
承知しました！お返事ありがとうございます。

**Comment by akira-hamada** [comment]
本件について、回答としては完了しておりますので、一旦issue closeさせていただきます。
