### ISSUE TITLE
請求書の更新APIに関しまして

### ISSUE THREAD

**Issue by katao** [moneyforward/invoice-api-doc#7]
請求書のAPIに関しまして
何点か質問をさせていだきます。
1.請求書登録APIにて請求書の作成と同時に登録した品目は、品目登録APIの品目と別ものなのでしょうか。管理画面の品目ページから見ても参照することができません。
2.請求書登録APIにて請求書の作成と同時に登録した品目は、請求書の更新APIにて更新可能でしょうか。また、その際keyとなる項目は[id]でしょうか。請求書の更新APIにて品目の付け替えや、品目追加を行おうとしております。
3.請求書の検索APIに関しまして、検索文字列の条件と期間絞込対象の条件は現在OR検索になっているかと思いますが、AND検索にできないでしょうか。
4.品目APIに関しまして
仕様書に記載されているレスポンスの"item"内の"item_code" : "ITEM-001"は、
"item_code"ではなく"code"かと思われます。
ご確認いただければと思います。

**Comment by syguer** [comment]
以下回答いたします。

> 1.請求書登録APIにて請求書の作成と同時に登録した品目は、品目登録APIの品目と別ものなのでしょうか。管理画面の品目ページから見ても参照することができません。

ご認識の通り、請求書作成時に登録した品目は、品目登録とは異なります。品目登録の方はあくまで品目マスタへの登録となります。

> 2.請求書登録APIにて請求書の作成と同時に登録した品目は、請求書の更新APIにて更新可能でしょうか。また、その際keyとなる項目は[id]でしょうか。請求書の更新APIにて品目の付け替えや、品目追加を行おうとしております。

更新可能です。
以下のようなjsonを`/api/v1/billnigs/更新したい請求書id`にPUTリクエストすると更新可能です。

```
{
  "items" : [
    {
      "name" : "追加したいitemのname。追加時はid不要"
    },
    {
      "id" : "更新したいitemのid",
      # 更新したいパラメーター #
    },
    {
      "id" : "削除したいitemのid",
      "_destroy" : true
    }
  ]
}
```
上記につきましては、次回ドキュメント更新時に追記させていただきます。

> 3.請求書の検索APIに関しまして、検索文字列の条件と期間絞込対象の条件は現在OR検索になっているかと思いますが、AND検索にできないでしょうか。

現状AND検索になっています。検索文字列及び期間の両方が条件となって検索されます。

> 4.品目APIに関しまして
仕様書に記載されているレスポンスの"item"内の"item_code" : "ITEM-001"は、
"item_code"ではなく"code"かと思われます。

ご指摘ありがとうございます。ご指摘の通りですので修正いたします。
